"""Initial migration

Revision ID: 1ac776fdae06
Revises: 
Create Date: 2026-04-02 12:22:31.116717

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1ac776fdae06'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chat_logs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('session_id', sa.String(length=64), nullable=False),
    sa.Column('user_message', sa.Text(), nullable=False),
    sa.Column('bot_reply', sa.Text(), nullable=True),
    sa.Column('is_agricultural', sa.Boolean(), nullable=False),
    sa.Column('is_greeting', sa.Boolean(), nullable=False),
    sa.Column('had_error', sa.Boolean(), nullable=False),
    sa.Column('response_ms', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('chat_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_chat_logs_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_chat_logs_session_id'), ['session_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_chat_logs_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chat_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_chat_logs_user_id'))
        batch_op.drop_index(batch_op.f('ix_chat_logs_session_id'))
        batch_op.drop_index(batch_op.f('ix_chat_logs_created_at'))

    op.drop_table('chat_logs')
    # ### end Alembic commands ###
