"""yield and risk

Revision ID: f594ae595bc2
Revises: 1ac776fdae06
Create Date: 2026-04-07 07:42:43.499318

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f594ae595bc2'
down_revision = '1ac776fdae06'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('analysis_history', schema=None) as batch_op:
        batch_op.drop_column('pest_risk_level')
        batch_op.drop_column('yield_predicted')
        batch_op.drop_column('yield_potential')
        batch_op.drop_column('yield_category')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('analysis_history', schema=None) as batch_op:
        batch_op.add_column(sa.Column('yield_category', sa.VARCHAR(length=30), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('yield_potential', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('yield_predicted', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('pest_risk_level', sa.VARCHAR(length=30), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
